FROM ubuntu:24.04

# Install core tools
RUN apt-get update && \
    apt-get install -y \
    python3 python3-venv python3-pip make bash emacs-nox docker-cli git && \
    ln -s /usr/bin/python3 /usr/bin/python && \
    rm -rf /var/lib/apt/lists/*

# Set up workdir
WORKDIR /workspace

# Run
CMD ["bash"]
