from typing import Self, Type, override

from sqlalchemy import Dialect
from sqlalchemy.sql import sqltypes as sqla
from sqlalchemy.sql.type_api import TypeEngine

from .adapter import TypeAdapter, Types

"""
Maps scoot_core.types.Types to SQLAlchemy TypeEngine types.
"""
SqlAlchemyTypes: dict[Types, Type] = {Types.STRING: sqla.String}


class SqlAlchemyType(TypeAdapter):
    """
    TypeAdapter implementation for SQLAlchemy TypeEngine types.
    """

    def __init__(self, type: TypeEngine):
        self.type = type

    def to_sqlalchemy_type(self) -> TypeEngine:
        return self.type

    @override
    def get_collation(self) -> str | None:
        """
        Get the collation of the SQLAlchemy type if applicable.

        Always returns None for types that are not of the `String`
        type hierarchy.

        Returns:
            str | None: The collation name if applicable, otherwise None.
        """
        if isinstance(self.type, sqla.String):
            return self.type.collation

        return None

    @override
    def get_precision(self) -> int | None:
        """
        Get the precision of the SQLAlchemy type if applicable.

        Returns:
            int | None: The precision value if applicable, otherwise None.
        """
        return getattr(self.type, "precision", None)

    @override
    def get_scale(self) -> int | None:
        """
        Get the scale of the SQLAlchemy type if applicable.

        Returns:
            int | None: The scale value if applicable, otherwise None.
        """
        return getattr(self.type, "scale", None)

    @override
    def get_timezone(self) -> str | None:
        """
        Get the timezone information of the SQLAlchemy type if applicable.

        Returns:
            str | None: The timezone information if applicable, otherwise None.
        """
        return getattr(self.type, "timezone", None)

    @override
    def is_type(self, type: Types) -> bool:
        """
        Check if the SQLAlchemy type matches the given Types enum.

        Args:
            type (Types): The type to check against.

        Returns:
            bool: True if the type matches, otherwise False.
        """
        return isinstance(self.type, SqlAlchemyTypes[type])

    @override
    def max_length(self) -> int | None:
        """
        Get the maximum length of the SQLAlchemy type if applicable.

        Returns:
            int | None: The maximum length if applicable, otherwise None.
        """
        if isinstance(self.type, sqla.String):
            return self.type.length

        return None

    @override
    def native_expression(self, dialect: Dialect) -> str:
        """
        Get the native type expression for the given SQL dialect.

        Native in this case refers to the syntax of the partiular SQL
        `dialect` as generated by SQLAlchemy.
        """
        return self.type.compile(dialect)

    @classmethod
    def from_alchemy_type(cls, type: TypeEngine) -> Self:
        """
        Create a SqlAlchemyType instance from a SQLAlchemy TypeEngine type.

        Args:
            type (TypeEngine): The SQLAlchemy type to adapt.

        Returns:
            SqlAlchemyType: An instance of SqlAlchemyType.
        """
        return cls(type)

    def __str__(self):
        """
        Get the string representation of the SQLAlchemy type.
        """
        return str(self.type)
